#!/bin/bash

if [ $# == 0 ] ; then
        read -p "Enter a username: " user_name
        read -sp "Enter a Password: " user_password
        echo""
        read -sp  "Enter the Password Again: " user_password_check ;

        if [ $user_password != $user_password_check ] ; then
        echo -e "\n $0 : Password mismatch!"
        exit 1;
        fi
else
        user_name="$1"
        read -sp "Enter Password: " user_password
        echo ""
        read -sp "Enter Password Again : " user_password_check
fi
echo -e "\n ++++++++++++++++++++++++++++++++++"
echo -e "\n \t  Username : $user_name"
echo -e "\t  Password : $user_password"
echo -e "\n ++++++++++++++++++++++++++++++++++"

useradd "$user_name"
echo "$user_password" | passwd --stdin $user_name;
echo "New user created!"
